### ISSUE TITLE
As a user, I want the website to know who I am so that I have a personalized experience

### ISSUE THREAD

**Issue by ZacharyBys** [justin-cotarla/CaptionThis#10]
### Priority: P1
- [x]  [` Database schema `](https://github.com/justin-cotarla/CaptionThis/issues/33)
- [x]  [` Database utility `](https://github.com/justin-cotarla/CaptionThis/issues/34)
- [x]  [` Login Backend `](https://github.com/justin-cotarla/CaptionThis/issues/36)
- [x]  [` Register Backend`](https://github.com/justin-cotarla/CaptionThis/issues/37)
- [x]  [` Logout `](https://github.com/justin-cotarla/CaptionThis/issues/38)
- [x]  [` Interact with state `](https://github.com/justin-cotarla/CaptionThis/issues/39)
- [x] [` Authentication utility `](https://github.com/justin-cotarla/CaptionThis/issues/42)
- [x]  [` Register Frontend `](https://github.com/justin-cotarla/CaptionThis/issues/45)
- [x]  [` Login Frontend `](https://github.com/justin-cotarla/CaptionThis/issues/46)

Due: Wednesday, February 14, 2018

Acceptance Test:
- When a user is not logged in
    - The user should not have access to moment creation page
    - The user should not have be able to post captions
    - The user should have access to the login page

- When a user is logged in
    - The user should have access to moment creation page, and create captions
    - The user should be able to post captions
    - The user should have access to the login page

- Registering
    - The user navigates to the register page
    - After registering, the user gets redirected to the main paged, logged in the created account

- Logging in
    - The user navigates to the login page
    - After logging, the user gets redirected to the main paged, logged in the account

**Comment by DYu24** [comment]
![image](https://user-images.githubusercontent.com/16171727/37236969-85e96196-23db-11e8-89ff-74e33a566480.png)
