### ISSUE TITLE
As a user, I want to be able to view my posts so that I can track my contribution

### ISSUE THREAD

**Issue by ZacharyBys** [justin-cotarla/CaptionThis#11]
### Story Points: 5
Users will have a sort of "profile" where they can track their contribution
- [x] [Profile page UI](https://github.com/justin-cotarla/CaptionThis/issues/102)
- [x] Moments the user has created
- [x] Captions the user has made on other moments

Due: Friday, February 23, 2018

Acceptance test: 
- User creates a moment
- User creates a caption for a different moment
- User navigates to .../username
- User views the moment and caption he posted

**Comment by DYu24** [comment]
![image](https://user-images.githubusercontent.com/16171727/38773674-9f352034-4020-11e8-950e-654d73202bc2.png)
