### ISSUE TITLE
As a user, I want to be able to create captions 

### ISSUE THREAD

**Issue by ZacharyBys** [justin-cotarla/CaptionThis#14]
### Story Point: 3
- [x] [`Create PUT captions endpoint`](https://github.com/justin-cotarla/CaptionThis/issues/60)
- [x] [`Create frontend captions component`](https://github.com/justin-cotarla/CaptionThis/issues/70)

Due: Wednesday, February 14, 2018

### Acceptance Test:
1. User logs into the website using their credentials or signs up if they do not yet have an account.
2. User navigates to a moment's page.
3. User enters a caption in the text area.
4. User submits their caption.
5. The newly created caption is displayed underneath the moment on the moment's page.

**Comment by DYu24** [comment]
![image](https://user-images.githubusercontent.com/16171727/37237032-1fd17f78-23dc-11e8-903f-8cfc3d71338f.png)
