### ISSUE TITLE
As a user, I want to be able to interact with captions

### ISSUE THREAD

**Issue by ZacharyBys** [justin-cotarla/CaptionThis#15]
### Story Points: 5

- [x] Up/downvote captions (frontend)
- [x] Create POST endpoint to update and return caption votes
- [x] Add accept/reject functionality to endpoint

Due: Wednesday, February 14, 2018

Acceptance test:
- User logs in
- User clicks on a moment on home page
- User scrolls to a specific caption
- User clicks on "+" vote button, see's the vote number go up
- User clicks on "-" vote button, see's the vote number go down
- User clicks on "accept" for caption, caption says It's accepted
- User clicks on "rejected" for caption, caption says It's rejected

**Comment by DYu24** [comment]
![image](https://user-images.githubusercontent.com/16171727/37237040-3e5243ba-23dc-11e8-8594-178bc35a6100.png)
