### ISSUE TITLE
As a user, I want to be able to view a moment and it's captions

### ISSUE THREAD

**Issue by ZacharyBys** [justin-cotarla/CaptionThis#16]
### Story Points: 5
* View moments
* View associated captions

- [x] Create get moment endpoint
- [x] Route to momentview page and display moment on moment click
- [x] Create caption component
- [x] Create get captions endpoint
- [x] Create caption list

Due: Wednesday, February 14, 2018

Acceptance test:
- User starts at home page
- User clicks on a moment
- User views specific moment and it's captions

**Comment by DYu24** [comment]
![image](https://user-images.githubusercontent.com/16171727/37237045-53c8b9cc-23dc-11e8-8fa2-12868c417b03.png)
