### ISSUE TITLE
[#10.3] Login Backend

### ISSUE THREAD

**Issue by croumeliotis** [justin-cotarla/CaptionThis#36]
Create a login page/model
- Takes username & password as input
- Validates inputs (ensures they are in the database)

Due date: Friday, February 9, 2018

**Comment by justin-cotarla** [comment]
Removed
- After validation: If account does not exist, redirect to registration
- After validation: If account exists, login (create session) and redirect to landing page.
- After successful login, enable user rights (ability to create moments, captions, etc.)
As they belong to frontend implementation
