### ISSUE TITLE
[#10.4] Registration Backend

### ISSUE THREAD

**Issue by croumeliotis** [justin-cotarla/CaptionThis#37]
Create registration page/model
- [x]  Takes username & password as input (Username must be unique)
- [x]  Validates inputs (ensures they are not already in the database)
- [x]  If account does not exist, create account in database

Due date: Thursday, February 8, 2018

**Comment by justin-cotarla** [comment]
I removed the following:
* If account already exists, prompt user for different username
* After account is created, automatically login user and redirect to landing page

Because they both belong to the frontend implementation.
